package com.example.rathaanelectronics.Rest;

public class ApiConstants {

    public static final String API_BASE_URL = "https://ecom.rathaan.com/api/";
    public static final String IMAGE_BASE_URL = "https://ecom.rathaan.com/uploads/";
    public static final String BASE_URL = "https://ecom.rathaan.com/";
    public static final String LG_APP_KEY = "lyfg@tApp";

    public static final String signup = "Auth/signup";
    public static final String signin = "Auth/loginuser";
    public static final String Forgot = "Rathaan/forgotpassword";
    public static final String TOPTWENTY = "Rathaan/toptwenty";
    public static final String HOTDEALS = "Rathaan/hotdeals";
    public static final String NEWARRIVALS = "Rathaan/newarrivals";
    public static final String BESTDEALS = "Rathaan/topseller";

    public static final String SLIDER = "Rathaan/sliderapi";

    public static final String PICKUPSTORELIST = "Rathaan/storelist";
    public static final String ALLCATEGORIES = "Rathaan/allcategories";
    public static final String SHOWWISHLIST = "Users/wishlistshow";
    public static final String SEARCHPRODUCT = "Rathaan/searchproduct";
    public static final String ADD_TO_CART = "Users/addtocart";
    public static final String BUNDLE_ADD_TO_CART = "Users/addtocartbundle";
    public static final String VIEW_CART = "Users/view_cart";
    public static final String WISH_LIST = "Users/wishlistshow";
    public static final String DELETE_WISH_LIST = "Users/deletewishlistitem";
    public static final String ADD_TO_WISH_LIST = "Users/wishlistadding";
    public static final String BUNDLE_DELETE_WISH_LIST = "Users/deletewishlistitem_bundle";
    public static final String BUNDLE_ADD_TO_WISH_LIST = "Users/wishlistadding_bundle";
    public static final String DELETE_CART_ITEM = "Users/removecartitem";
    public static final String CHANGE_CART_QUANTITY = "Users/changecartqty";
    public static final String PROD_DETAILS = "Rathaan/proddetails";
    public static final String GUEST_TOKEN = "Auth/guest_login";
    public static final String ADD_TO_COMPARE = "Users/compare_adding";
    public static final String REMOVE_COMPARE = "Users/removecompare";
    public static final String LIST_COMPARE = "Users/showcompare";
    public static final String ADD_ADDRESS = "Users/addresssave";
    public static final String UPDATE_ADDRESS = "Users/updateadrs";
    public static final String SHOW_ADDRESS = "Users/addresslist";
    public static final String DELETE_ADDRESS = "Users/delete_address";
    public static final String APPLY_COUPON = "Users/apply_coupon";
    public static final String PERSONAL_INFO = "Users/personal_info";
    public static final String PERSONAL_INFO_EDIT = "Users/personal_info_edit";
    public static final String CART_COUNT = "Users/getcartcoundandamount";
    public static final String CAT_PRODUCT = "Rathaan/category_products";
    public static final String SUB_CAT_PRODUCT = "Rathaan/subcategory_products";
    public static final String HOME_OFFER_BANNER = "Rathaan/getofferbanner";
    public static final String HOME_TIMER_OFFER = "Rathaan/home_timeroffers";
    public static final String HOME_NON_TIMER_OFFER = "Rathaan/home_non_timeroffers";
    public static final String HOME_BEST_DEALS_CATEGORIES = "Rathaan/home_bestdeals_cats";
    public static final String HOME_BEST_DEALS_CATEGORY_WISE = "Rathaan/home_bestdeals_catwise";
    public static final String DEALS_AND_OFFERS = "Rathaan/deals_and_offers";
    public static final String LIST_BUNDLE_PRODUCTS = "Rathaan/bundle_products";
    public static final String COUPON_APPLY = "Users/couponapply";
    public static final String POINTS = "Users/walletandloyaltyforcheckout";
    public static final String GOVERNARATE_LIST = "Rathaan/governarate_list";
    public static final String AREA_LIST = "Rathaan/governarate_area_list";
    public static final String CHECK_OUT = "Users/precheckout";
    public static final String DEL_CHARGE = "Users/setdelcharg";
    public static final String DEL_CHECK = "Users/selected_deldate_check";
    public static final String DEL_AVAILABILITY_CHECK = "Users/delivery_availablities";
    public static final String CHECKOUT_AVAILABILITY_CHECK = "Users/checkout_availablity";
    public static final String DEL_DAYS_AVAILABILITY_CHECK = "Users/delivery_seting";
    public static final String ORDER_HISTORY = "Users/orderhistorylist";
    public static final String ORDER_DETAILS = "Users/orderdetails";
    public static final String RETURN_REASONS = "Users/orderreturnreasons";
    public static final String RETURN_REQUEST = "Users/orderreturnrequest";
    public static final String NOTIFICATIONS = "Users/notifications";
    public static final String WALLET = "Users/wallet";
    public static final String LOYALTY_POINTS = "Users/loyaltypoints";
    public static final String BUNDLE_DETAILS = "Rathaan/single_bundle_product";
    public static final String WALLET_APPLIED = "Users/walletapplied_checkout_amount";
    public static final String LOYALTY_APPLIED = "Users/loyaltyapplied_checkout_amount";
    public static final String RETURN_POLICY = "Rathaan/returnpolicy";
    public static final String RETURN_POLICY_MAIL = "Rathaan/returnpolicy_mail";
    public static final String CONTACT_MAIL_SEND = "Rathaan/contactmail_send";
    public static final String TERMS_CONDITIONS = "Rathaan/termsandconditions";
}
